// localStorage.clear();

const employees = [
  {
    id: 1,
    fname: "Aarav",
    lname: "Sharma",
    email: "employee1@company.com",
    password: "123",
    taskNumbers: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Prepare sales report",
        description: "Compile and analyze monthly sales data",
        date: "2026-01-05",
        category: "Reporting",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Create marketing presentation",
        description: "Design slides for upcoming product launch",
        date: "2026-01-06",
        category: "Marketing",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Client follow-up",
        description: "Follow up with potential clients via email",
        date: "2026-01-07",
        category: "Communication",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Update CRM",
        description: "Update customer records in CRM system",
        date: "2026-01-10",
        category: "Data Entry",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 2,
    fname: "Rohit",
    lname: "Verma",
    email: "employee2@company.com",
    password: "123",
    taskNumbers: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Design homepage banner",
        description: "Create a new banner for the homepage",
        date: "2026-01-06",
        category: "Design",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Fix UI bugs",
        description: "Resolve reported UI layout issues",
        date: "2026-01-08",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Create mobile mockups",
        description: "Design responsive layouts for mobile devices",
        date: "2026-01-09",
        category: "Design",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Review design feedback",
        description: "Incorporate feedback from product team",
        date: "2026-01-12",
        category: "Review",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Export assets",
        description: "Export final assets for developers",
        date: "2026-01-14",
        category: "Design",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 3,
    fname: "Sanjay",
    lname: "Mehta",
    email: "employee3@company.com",
    password: "123",
    taskNumbers: {
      active: 2,
      newTask: 1,
      completed: 2,
      failed: 1,
    },
    tasks: [
      {
        title: "Write API documentation",
        description: "Document authentication APIs",
        date: "2026-01-04",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Implement login feature",
        description: "Develop login functionality",
        date: "2026-01-09",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Code review",
        description: "Review pull requests from teammates",
        date: "2026-01-11",
        category: "Review",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Setup CI/CD pipeline",
        description: "Configure automated deployment workflow",
        date: "2026-01-12",
        category: "DevOps",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix authentication bug",
        description: "Resolve token expiration issue",
        date: "2026-01-13",
        category: "Bug Fix",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Optimize queries",
        description: "Improve database query performance",
        date: "2026-01-15",
        category: "Optimization",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    fname: "Priya",
    lname: "Iyer",
    email: "employee4@company.com",
    password: "123",
    taskNumbers: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        title: "Prepare onboarding material",
        description: "Create slides for new hires",
        date: "2026-01-03",
        category: "HR",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Schedule interviews",
        description: "Arrange interview slots for candidates",
        date: "2026-01-06",
        category: "Recruitment",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Update employee records",
        description: "Ensure all employee data is up to date",
        date: "2026-01-10",
        category: "HR",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Review job applications",
        description: "Screen resumes for open positions",
        date: "2026-01-11",
        category: "Recruitment",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    fname: "Neha",
    lname: "Kapoor",
    email: "employee5@company.com",
    password: "123",
    taskNumbers: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Test payment gateway",
        description: "Perform end-to-end payment testing",
        date: "2026-01-05",
        category: "Testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Log bugs",
        description: "Report discovered bugs in Jira",
        date: "2026-01-07",
        category: "QA",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Regression testing",
        description: "Test existing features after updates",
        date: "2026-01-11",
        category: "Testing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Write test cases",
        description: "Document test scenarios for new features",
        date: "2026-01-13",
        category: "QA",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Automation script update",
        description: "Update test automation scripts",
        date: "2026-01-14",
        category: "Automation",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    fname: "Rakesh",
    lname: "Malhotra",
    email: "admin@company.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
